1. Import all the required Python Libraries.
2. Locate open source data from the web (e.g.,  https://www.kaggle.com). Provide a clear description of the data and its source (i.e., URL of the web site).
3. Load the Dataset into pandas dataframe

In [ ]:
#Import Tabular Data from CSV Files into Pandas Dataframes
import pandas as pd
df= pd.read_csv("C:/Users/Admin/Documents/DSBDAL/Lab/Experiments/Datasets/13data.csv")
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

4.Data Preprocessing: check for missing values in the data using pandas isnull()

In [ ]:
df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df['Sex'].value_counts()

1    577
0    314
Name: Sex, dtype: int64

In [ ]:
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1
2                               Heikkinen, Miss. Laina    0  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1
4                             Allen, Mr. William Henry    1  35.0      0
..                                                 ...  ...   ...    ...
886                              Montvila, Rev. Juozas    1  27.0      0
887                       Graham, Miss. Margaret Edith    0  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"    0   NaN      1
889                              Behr, Mr. Karl Howell    1  26.0      0
890                                Dooley, Mr. Patrick    1  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [ ]:
df.isnull()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.isnull().sum().sum()
#returns the number of missing values in the dataset.

866

In [ ]:
df.isnull()
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

#describe() function to get some initial statistics

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.describe(include=['object'])

                             Name   Sex Ticket    Cabin Embarked
count                         891   891    891      204      889
unique                        891     2    681      147        3
top     Reynaldo, Ms. Encarnacion  male   1601  B96 B98        S
freq                            1   577      7        4      644

Provide variable descriptions. Types of variables

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df.head(20)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",1,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",1,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",1,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",0,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",0,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",0,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",0,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",1,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",1,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",0,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",0,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",1,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",1,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",0,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",0,NaN,0,0,2649,7.2250,NaN,C

In [ ]:
#Check the dimensions of the data frame
df.shape

(891, 12)

In [ ]:
#number of rows of a DataFrame
len(df)

891

In [ ]:
#total number of elements in the DataFrame
df.size

10692

Data Formatting and Data Normalization: Summarize the types of variables by checking the data types (i.e., character, numeric, integer, factor, and logical) of the variables in the data set. If variables are not in the correct data type, apply proper type conversions

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Summarize the types of variables by checking the data types (i.e., character, numeric, integer, factor, and logical) of the variables in the data set.

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

If variables are not in the correct data type, apply proper type conversions......Age--float64--int

In [ ]:
df['Age']=df['Age'].fillna(20)
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female  20.0      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [ ]:
df['Age'] = df['Age'].astype('int64')
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age              int64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

Turn categorical variables into quantitative variables in Python

In [ ]:
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [ ]:
dummies = pd.get_dummies(df.Sex)
merged = pd.concat([df, dummies], axis='columns')
print(merged)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked  female  male
0        0         A/5 21171   7.2500   NaN        S       0     1
1        0          PC 17599  71.2833   C85        C       1     0
2        0  STON/O2. 3101282   7.9250   NaN        S       1     0
3        0            113803  53.1000  C123        S       1     0
4        0            373450   8.0500   NaN        S       0     1
..     ...               ...      ...   ...      ...     ...   ...
886      0            211536  13.0000   NaN        S       0     1
887      0            112053  30.0000   B42        S       1     0
888      2        W./C. 6607  23.4500   NaN        S       1     0
889      0            111369  30.0000  C148        C       0     1
890      0            370376   7.7500   NaN        Q       0     1

[891 rows x 14 columns]

In [ ]:
dummies = pd.get_dummies(df.Embarked)
m = pd.concat([df, dummies], axis='columns')
print(m)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked  C  Q  S
0        0         A/5 21171   7.2500   NaN        S  0  0  1
1        0          PC 17599  71.2833   C85        C  1  0  0
2        0  STON/O2. 3101282   7.9250   NaN        S  0  0  1
3        0            113803  53.1000  C123        S  0  0  1
4        0            373450   8.0500   NaN        S  0  0  1
..     ...               ...      ...   ...      ... .. .. ..
886      0            211536  13.0000   NaN        S  0  0  1
887      0            112053  30.0000   B42        S  0  0  1
888      2        W./C. 6607  23.4500   NaN        S  0  0  1
889      0            111369  30.0000  C148        C  1  0  0
890      0            370376   7.7500   NaN        Q  0  1  0

[891 rows x 15 columns]

In [ ]:
dummies = pd.get_dummies(df.Sex)
merged = pd.concat([df, dummies], axis='columns')
merged.drop(['Sex'], axis='columns')

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,1,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,1,0
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,S,0,1
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,S,1,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,2,W./C. 6607,23.4500,NaN,S,1,0
889,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,C,0,1
890,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,Q,0,1

In [ ]:
df["Embarked_cat"] = df["Embarked"].astype('category')
df["Embarked_num"] = df["Embarked_cat"].cat.codes
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Embarked_cat,Embarked_num
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,S,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,S,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,S,2
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,S,2
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,S,2
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Q,1

In [ ]:
from sklearn.preprocessing import LabelEncoder
# creating instance of labelencoder
labelencoder = LabelEncoder()
# Assigning numerical values and storing in another column
df['LEE'] = labelencoder.fit_transform(df["Sex"])
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked  LEE
0        0         A/5 21171   7.2500   NaN        S    1
1        0          PC 17599  71.2833   C85        C    0
2        0  STON/O2. 3101282   7.9250   NaN        S    0
3        0            113803  53.1000  C123        S    0
4        0            373450   8.0500   NaN        S    1
..     ...               ...      ...   ...      ...  ...
886      0            211536  13.0000   NaN        S    1
887      0            112053  30.0000   B42        S    0
888      2        W./C. 6607  23.4500   NaN        S    0
889      0            111369  30.0000  C148        C    1
890      0            370376   7.7500   NaN        Q    1

[891 rows x 13 columns]

In [ ]:
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1
2                               Heikkinen, Miss. Laina    1  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1
4                             Allen, Mr. William Henry    0  35.0      0
..                                                 ...  ...   ...    ...
886                              Montvila, Rev. Juozas    0  27.0      0
887                       Graham, Miss. Margaret Edith    1  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"    1   NaN      1
889                              Behr, Mr. Karl Howell    0  26.0      0
890                                Dooley, Mr. Patrick    0  32.0      0

     Parch            Ticket     Fare Cabin Embarked Embarked_cat  \
0        0         A/5 21171   7.2500   NaN        S            S
1        0          PC 17599  71.2833   C85        C            C
2        0  STON/O2. 3101282   7.9250   NaN        S            S
3        0            113803  53.1000  C123        S            S
4        0            373450   8.0500   NaN        S            S
..     ...               ...      ...   ...      ...          ...
886      0            211536  13.0000   NaN        S            S
887      0            112053  30.0000   B42        S            S
888      2        W./C. 6607  23.4500   NaN        S            S
889      0            111369  30.0000  C148        C            C
890      0            370376   7.7500   NaN        Q            Q

     Embarked_num  LEE
0               2    0
1               0    1
2               2    1
3               2    1
4               2    0
..            ...  ...
886             2    0
887             2    1
888             2    1
889             0    0
890             1    0

[891 rows x 15 columns]

In [ ]:
df['LEE'].value_counts()

1    577
0    314
Name: LEE, dtype: int64

In [ ]:
df['Sex'].value_counts()

1    577
0    314
Name: Sex, dtype: int64

In [ ]:
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1
2                               Heikkinen, Miss. Laina    1  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1
4                             Allen, Mr. William Henry    0  35.0      0
..                                                 ...  ...   ...    ...
886                              Montvila, Rev. Juozas    0  27.0      0
887                       Graham, Miss. Margaret Edith    1  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"    1   NaN      1
889                              Behr, Mr. Karl Howell    0  26.0      0
890                                Dooley, Mr. Patrick    0  32.0      0

     Parch            Ticket     Fare Cabin Embarked Embarked_cat  \
0        0         A/5 21171   7.2500   NaN        S            S
1        0          PC 17599  71.2833   C85        C            C
2        0  STON/O2. 3101282   7.9250   NaN        S            S
3        0            113803  53.1000  C123        S            S
4        0            373450   8.0500   NaN        S            S
..     ...               ...      ...   ...      ...          ...
886      0            211536  13.0000   NaN        S            S
887      0            112053  30.0000   B42        S            S
888      2        W./C. 6607  23.4500   NaN        S            S
889      0            111369  30.0000  C148        C            C
890      0            370376   7.7500   NaN        Q            Q

     Embarked_num  LEE
0               2    0
1               0    1
2               2    1
3               2    1
4               2    0
..            ...  ...
886             2    0
887             2    1
888             2    1
889             0    0
890             1    0

[891 rows x 15 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['LEE'] = le.fit_transform(df['Sex'])
print(le.classes_)

[0 1]

In [ ]:
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1
2                               Heikkinen, Miss. Laina    1  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1
4                             Allen, Mr. William Henry    0  35.0      0
..                                                 ...  ...   ...    ...
886                              Montvila, Rev. Juozas    0  27.0      0
887                       Graham, Miss. Margaret Edith    1  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"    1   NaN      1
889                              Behr, Mr. Karl Howell    0  26.0      0
890                                Dooley, Mr. Patrick    0  32.0      0

     Parch            Ticket     Fare Cabin Embarked Embarked_cat  \
0        0         A/5 21171   7.2500   NaN        S            S
1        0          PC 17599  71.2833   C85        C            C
2        0  STON/O2. 3101282   7.9250   NaN        S            S
3        0            113803  53.1000  C123        S            S
4        0            373450   8.0500   NaN        S            S
..     ...               ...      ...   ...      ...          ...
886      0            211536  13.0000   NaN        S            S
887      0            112053  30.0000   B42        S            S
888      2        W./C. 6607  23.4500   NaN        S            S
889      0            111369  30.0000  C148        C            C
890      0            370376   7.7500   NaN        Q            Q

     Embarked_num  LEE
0               2    0
1               0    1
2               2    1
3               2    1
4               2    0
..            ...  ...
886             2    0
887             2    1
888             2    1
889             0    0
890             1    0

[891 rows x 15 columns]

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object